version: "3.3"
services:
  server:
    build:
        context: ./server
        dockerfile: Dockerfile
    env_file:
        - ./server/.env
    volumes:
        - ./server:/usr/src/app/
        - server_node_modules:/usr/src/app/node_modules
    ports:
        - "3000:3000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app/
      - client_node_modules:/usr/src/app/node_modules
    ports:
      - "8888:80"
volumes:
  client_node_modules:
  server_node_modules:
